/**
 * Pure JSDoc inventory extractor.  Tag names and the sole writable artifact are
 * repository policy, not a baked-in component library or design-document model.
 */
export interface SourceFile { readonly path: string; readonly content: string; }
export interface InventoryTags { readonly component: string; readonly whenToUse: string; readonly slot: string; readonly directive: string; }
export interface ComponentSlot { readonly name: string; readonly description: string; }
export interface ComponentEntry { readonly component: string; readonly source: string; readonly whenToUse?: string; readonly slots: ReadonlyArray<ComponentSlot>; readonly directives: ReadonlyArray<string>; }
export type InventoryResult = {readonly pass: true; readonly entries: ReadonlyArray<ComponentEntry>} | {readonly pass: false; readonly reason: "zero-scope"};
const normalize = (value: string): string => value.replace(/\s+/g, " ").trim();
const blocks = (content: string): ReadonlyArray<string> => Array.from(content.matchAll(/\/\*\*([\s\S]*?)\*\//g), (match) => (match[1] ?? "").split("\n").map((line) => line.replace(/^\s*\*?\s?/, "")).join("\n"));
interface Tag {readonly name: string; readonly value: string;}
const tags = (block: string): ReadonlyArray<Tag> => {
	const out: Array<{name: string; values: string[]}> = []; let current: {name: string; values: string[]} | undefined;
	for (const line of block.split("\n")) { const match = /^@(\w+)\s*(.*)$/.exec(line); if (match) { current = {name: match[1] ?? "", values: [match[2] ?? ""]}; out.push(current); } else if (current) current.values.push(line); }
	return out.map((item) => ({name: item.name, value: item.values.join("\n")}));
};
const slot = (value: string): ComponentSlot => { const normalized = normalize(value); const index = normalized.search(/\s/); return index < 0 ? {name: normalized, description: ""} : {name: normalized.slice(0, index), description: normalized.slice(index + 1)}; };
export const extractFromFile = (file: SourceFile, configured: InventoryTags): ReadonlyArray<ComponentEntry> => blocks(file.content).flatMap((block) => {
	const parsed = tags(block); const component = normalize(parsed.find((tag) => tag.name === configured.component)?.value ?? "").split(/\s+/)[0] ?? "";
	if (!component) return [];
	const whenToUse = parsed.find((tag) => tag.name === configured.whenToUse)?.value;
	return [{component, source: file.path, ...(whenToUse ? {whenToUse: normalize(whenToUse)} : {}), slots: parsed.filter((tag) => tag.name === configured.slot).map((tag) => slot(tag.value)), directives: parsed.filter((tag) => tag.name === configured.directive).map((tag) => normalize(tag.value)).filter(Boolean)}];
});
export const buildInventory = (files: ReadonlyArray<SourceFile>, configured: InventoryTags): InventoryResult => {
	const entries = files.flatMap((file) => extractFromFile(file, configured)).sort((a, b) => a.component.localeCompare(b.component) || a.source.localeCompare(b.source));
	return entries.length ? {pass: true, entries} : {pass: false, reason: "zero-scope"};
};
export const renderInventory = (entries: ReadonlyArray<ComponentEntry>, artifactPath: string): string => {
	const sections = entries.map((entry) => {
		const lines = [`## ${entry.component}`, "", `_Source: ${entry.source}_`, ""];
		if (entry.whenToUse) lines.push(`**When to use:** ${entry.whenToUse}`, "");
		if (entry.slots.length) { lines.push("**Slots:**"); for (const item of entry.slots) lines.push(item.description ? `- \`${item.name}\` — ${item.description}` : `- \`${item.name}\``); lines.push(""); }
		if (entry.directives.length) { lines.push("**Configured directives:**"); for (const directive of entry.directives) lines.push(`- ${directive}`); lines.push(""); }
		return lines.join("\n").trimEnd();
	});
	return [`# Design system — descriptive inventory`, "", `<!-- GENERATED by \`pipeline-cli design-inventory generate\` for \`${artifactPath}\` — do not hand-edit. -->`, "", "This is a generated descriptive index. Repository policy owns the source scope, tag vocabulary, and any normative design documents; generation never rewrites those documents.", "", ...sections].join("\n") + "\n";
};
