/**
 * standup/ — the launcher: boot the whole crew from the operator config. This barrel is the module's
 * one public surface, re-exporting every launcher primitive and the `runStandUp` orchestration that
 * composes them in order (version-assert → ensure-tracker → roster session-set → per-session bind →
 * tmux placement → launch), fail-loud with no partial crew (the crew-start rule: derive and launch the configured roster from one validated config, the atomic stand-up rule: launch the complete roster or fail without leaving a partial crew).
 */
export {
	ALLOWLIST_CHANNEL_FLAG,
	buildSessionBind,
	ChannelPluginNotAllowedError,
	CREW_SESSION_BIN_PATH,
	CREW_SESSION_COMMAND,
	CREW_SESSION_INSTANCE_FLAG,
	type CrewServerConfig,
	CrewServerNotRegisteredError,
	CrewSessionBinUnresolvableError,
	DEV_CHANNEL_FLAG,
	MODEL_FLAG,
	NAME_FLAG,
	type SessionBind,
	type SessionBindInput,
} from "./bind.ts";
export {
	CHANNEL_PLUGIN_REF_RE,
	CHANNEL_SERVER_REF_RE,
	ChannelConfig,
	ChannelMode,
	ChannelServerRef,
	CLI_VERSION_RE,
	CliVersion,
	DEFAULT_CONFIG_PATH,
	DEFAULT_TERMINAL,
	decodeLaunchConfig,
	EngineCount,
	LaunchConfig,
	LaunchConfigError,
	parseJsonc,
	readLaunchConfig,
	resolveConfigPath,
	resolveProjectConfigPath,
	stripJsonc,
	TERMINAL_KINDS,
	TerminalKind,
} from "./config.ts";
export {
	closeHerdrPane,
	CREW_TAB_LABEL,
	FALLBACK_HERDR_WORKSPACE,
	findCrewPaneIdInHerdr,
	type HerdrRun,
	type HerdrRunner,
	herdrPaneCommand,
	herdrResult,
	launchSessionInHerdr,
	resolveCrewTabId,
	resolveTargetHerdrWorkspace,
	runHerdr,
} from "./herdr.ts";
export {
	ensureTrackerRunning,
	runStandingTracker,
	type TrackerBindOutcome,
	type TrackerHandle,
	TrackerNotServingError,
	tryBecomeTracker,
} from "./ensure-tracker.ts";
export {
	buildLaunchPlan,
	CREW_WINDOW,
	ensureNamedTmuxSession,
	FALLBACK_TMUX_SESSION,
	type LaunchedSession,
	type LaunchPlan,
	launchSessionInTmux,
	type ProjectScopeRegisterInput,
	type ProjectScopeRegistrar,
	paneClaudeCommand,
	productionProjectScopeRegistrar,
	renderStandUpError,
	renderTaggedError,
	resolveTargetTmuxSession,
	runStandDown,
	runStandUp,
	runTmux,
	type SessionPlanContext,
	type StandDownInput,
	type StandUpError,
	type StandUpInput,
	StandUpLaunchError,
	type StandUpResult,
	type TmuxRun,
	type TmuxRunner,
	TmuxSessionEnsureError,
	toRosterSession,
} from "./orchestrate.ts";
export {
	applyDisableApproval,
	applyEnableApproval,
	applyTrust,
	assertNoSharedAncestorMcpJson,
	buildMcpJsonContent,
	CREW_RUN_DIR,
	type CrewMcpEntry,
	claudeConfigPath,
	crewRunRoot,
	disableCrewServerApproval,
	enableCrewServerApproval,
	ensureCrewRunPrefix,
	ensureFolderTrusted,
	ensurePaneCwd,
	MCP_JSON_FILENAME,
	mcpJsonPath,
	ProjectScopeWriteError,
	type RegisterCrewProjectScopeInput,
	reapCrewProjectScopeFor,
	registerCrewProjectScope,
	resolveGitRoot,
	sharedAncestorDirs,
	userSettingsPath,
	withLockedJsonFile,
	writeCrewMcpJson,
} from "./register-project-scope.ts";
export {
	type BridgeSession,
	type CrewSession,
	deriveOneSession,
	deriveSessionSet,
	type EngineSession,
	type SessionSetInput,
} from "./session-set.ts";
export {
	CrewPaneKillError,
	CrewPaneNotFoundError,
	CrewWindowNotRunningError,
	findCrewPaneId,
	productionRetireArtifacts,
	type RetireArtifacts,
	RetireRoleArgError,
	type RetireRoleError,
	type RetireRoleInput,
	type RetireRoleResult,
	resolveCrewWindowId,
	retireRole,
	type SpawnRoleError,
	type SpawnRoleInput,
	type SpawnRoleResult,
	spawnRole,
} from "./single-role.ts";
export {
	herdrBackend,
	TERMINAL_BACKENDS,
	type TerminalBackend,
	terminalBackend,
	tmuxBackend,
} from "./terminal.ts";
export {
	computeTmuxPlacement,
	type PlacementTarget,
	type RosterSession,
	TmuxPaneCollisionError,
} from "./tmux-placement.ts";
export {
	assertPinnedCliVersion,
	CliVersionAssertError,
	parseCliVersion,
	readInstalledCliVersionOutput,
} from "./version-assert.ts";
